language: php 

compiler:
  - gcc
  - clang

os:
  - linux
#  - osx

php:
  - 5.4
  - 5.5
  - 7.0
   
env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

#Compile
before_script:
    - chmod +x travis
    - travis/compile.sh

script:
    - exit 0


